# Autogenerated file
def render(name):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Configuration Editor</title>
</head>
<body>
    <h1>Edit Configuration</h1>
    <form id=\"configForm\">
        """
    for key in name.keys():
        yield """            <label for=\""""
        yield str(key)
        yield """\">"""
        yield str(key)
        yield """:</label>
            <input type=\"text\" id=\""""
        yield str(key)
        yield """\" name=\""""
        yield str(key)
        yield """\" value=\""""
        yield str(name[key])
        yield """\" size=\"50\">
            <br><br>
        """
    yield """        <button type=\"button\" onclick=\"submitConfig()\">Save Changes</button>
    </form>

    <script>
        function submitConfig() """
    yield """{
            const form = document.getElementById('configForm');
            const formData = """
    yield """{};

            // Gather form data
            Array.from(form.elements).forEach(element => """
    yield """{
                if (element.name) """
    yield """{
                    formData[element.name] = element.value;
                }
            });

            // Send JSON HTTP POST request
            fetch('/', """
    yield """{
                method: 'POST',
                headers: """
    yield """{
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(formData)
            })
            .then(response => response.json())
            .then(data => """
    yield """{
                console.log('Success:', data);
            })
            .catch((error) => """
    yield """{
                console.error('Error:', error);
            });
        }
    </script>
</body>
</html>
"""
